Repository Step3-kakao-tech-campus/Team11_FE, pull requests merged in 2023-11, with the labels that each got.

#196 fix: 카테고리 정렬 문제 해결
  Goalajuma/src/components/layouts/headers/CategoryBox.jsx
  Goalajuma/src/pages/complete/CompletePage.jsx
  Goalajuma/src/pages/main/MainPage.jsx
Labels: fix

#194 feat: 투표 상세 페이지 조회 api 연결
  Goalajuma/src/App.jsx
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/common/modal/ModalTest.js
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
  Goalajuma/src/components/home/HomeLayout.jsx
  Goalajuma/src/pages/login/LoginPage.jsx
  Goalajuma/src/pages/signup/SignUpPage.jsx
  Goalajuma/src/services/login.js
  Goalajuma/src/services/main.js
Labels: 🔨 bug, 🔥 feature

#198 fix: 메인페이지, 완료페이지 카테고리 정렬 분리
  Goalajuma/src/components/layouts/headers/CompleteCategoryBox.jsx
  Goalajuma/src/components/layouts/headers/Main.jsx
  Goalajuma/src/pages/complete/CompletePage.jsx
  Goalajuma/src/pages/main/MainPage.jsx
  Goalajuma/src/utils/HeaderAtom.js
Labels: fix

#202 feat: 검색 모달창 구현
  Goalajuma/src/components/common/modal/Modal.jsx
  Goalajuma/src/components/home/HomeLayout.jsx
  Goalajuma/src/components/layouts/headers/CategoryBox.jsx
  Goalajuma/src/components/layouts/headers/SearchButton.jsx
  Goalajuma/src/components/search/SearchInput.jsx
  Goalajuma/src/components/search/SearchModal.jsx
  Goalajuma/src/pages/hot/HotPage.jsx
  Goalajuma/src/pages/search/SearchPage.jsx
  Goalajuma/src/services/main.js
Labels: 🔥 feature

#200 fix: 투표 상세 조회 id 추출
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
  Goalajuma/src/components/home/HomeLayout.jsx
Labels: 🔨 bug, help wanted

#204 fix: 검색창 버그 수정
  Goalajuma/src/components/common/Icon.jsx
  Goalajuma/src/components/search/SearchInput.jsx
  Goalajuma/src/components/search/SearchModal.jsx
  Goalajuma/src/pages/search/SearchPage.jsx
Labels: 🔨 bug

#209 feat: 페이지에 데이터 없을 경우 처리
  Goalajuma/src/components/common/NonePage.jsx
  Goalajuma/src/components/common/modal/Modal.jsx
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/home/HomeLayout.jsx
  Goalajuma/src/pages/complete/CompletePage.jsx
  Goalajuma/src/pages/main/MainPage.jsx
  Goalajuma/src/pages/search/SearchPage.jsx
Labels: 🔨 bug, fix

#211 bug: 마이페이지 연결
  Goalajuma/src/pages/my/Mypage.jsx
  Goalajuma/src/pages/my/ProfileModal.jsx
Labels: 🔨 bug

#212 feat: 에러 수정 및 개발
  Goalajuma/src/App.jsx
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/common/modal/ShareForm.jsx
  Goalajuma/src/components/home/HomeLayout.jsx
  Goalajuma/src/components/login/InputGroup.jsx
  Goalajuma/src/main.jsx
  Goalajuma/src/pages/login/LoginPage.jsx
  Goalajuma/src/pages/signup/SignUpPage.jsx
  Goalajuma/src/services/login.js
  Goalajuma/src/services/main.js
Labels: 🔨 bug, 🔥 feature, fix

#217 fix: 회원가입 중복버튼 디자인 수정
  Goalajuma/src/components/login/Label.jsx
  Goalajuma/src/pages/signup/SignUpPage.jsx
Labels: fix

#232 fix: 메인 모달창 높이 수정
  Goalajuma/src/components/common/ScrollToTop.js
  Goalajuma/src/components/common/modal/ChatForm.jsx
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/home/MainContent.jsx
  Goalajuma/src/main.jsx
  Goalajuma/src/pages/main/MainPage.jsx
  Goalajuma/src/pages/upload/UploadPage.jsx
  Goalajuma/src/services/main.js
  Goalajuma/src/styles/Container.jsx
Labels: fix

#236 fix: 카테고리 리팩토링
  Goalajuma/src/components/layouts/headers/CategoryBox.jsx
  Goalajuma/src/components/layouts/headers/CompleteCategoryBox.jsx
  Goalajuma/src/components/layouts/headers/DropdownList.jsx
  Goalajuma/src/utils/HeaderAtom.js
Labels: 🌱 refactoring

#242 feat: 투표 마감 api 연결 및 토큰 관리
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/common/voteButton/EndButton.jsx
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
  Goalajuma/src/components/home/HomeLayout.jsx
  Goalajuma/src/hooks/useLogin.js
  Goalajuma/src/pages/login/LoginPage.jsx
  Goalajuma/src/pages/my/ProfileModal.jsx
  Goalajuma/src/services/Cookie.js
  Goalajuma/src/services/index.js
  Goalajuma/src/services/login.js
  Goalajuma/src/services/main.js
  Goalajuma/src/utils/AuthAtom.js
Labels: 🔨 bug, 🔥 feature, help wanted, fix

#246 feat: 투표 종료 api 연결 및 로그인 토큰 관리
  Goalajuma/src/components/common/voteButton/EndButton.jsx
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
  Goalajuma/src/hooks/useLogin.js
  Goalajuma/src/pages/my/ProfileModal.jsx
  Goalajuma/src/services/index.js
  Goalajuma/src/services/login.js
  Goalajuma/src/services/main.js
Labels: 🔥 feature, fix

#253 fix: refresh Token 요청
  Goalajuma/src/components/common/voteButton/EndButton.jsx
  Goalajuma/src/services/index.js
  Goalajuma/src/services/login.js
Labels: 🔨 bug

#257 fix: 수정사항
  Goalajuma/package-lock.json
  Goalajuma/package.json
  Goalajuma/src/App.jsx
  Goalajuma/src/components/common/Alert.jsx
  Goalajuma/src/components/common/NonePage.jsx
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/common/modal/ModalTemplate.jsx
  Goalajuma/src/components/common/voteButton/ButtonLayout.jsx
  Goalajuma/src/components/common/voteButton/EndButton.jsx
  Goalajuma/src/components/home/HomeLayout.jsx
  Goalajuma/src/components/template/CompleteTemplate.jsx
  Goalajuma/src/components/template/HomeTemplate.jsx
  Goalajuma/src/components/template/HotTemplate.jsx
  Goalajuma/src/components/upload/UploadButton.jsx
  Goalajuma/src/pages/hot/HotPage.jsx
  Goalajuma/src/pages/main/MainPage.jsx
  Goalajuma/src/pages/upload/UploadPage.jsx
  Goalajuma/src/routes.js
  Goalajuma/src/services/main.js
  Goalajuma/src/styles/Container.jsx
  Goalajuma/src/utils/ToastAtom.js
Labels: 🔨 bug, fix

#280 feat: 댓글 삭제 기능
  src/components/common/modal/Chat.jsx
  src/components/common/modal/ChatBeta.jsx
  src/components/common/modal/ModalTemplate.jsx
Labels: 🔥 feature

#282 fix: 투표 종료 성공 및 메인 화면 공유 기능 제거
  src/components/common/Icon.jsx
  src/components/common/modal/ModalTemplate.jsx
  src/components/common/voteButton/EndButton.jsx
  src/components/common/voteButton/VoteBottom.jsx
  src/components/home/HomeLayout.jsx
Labels: 🔥 feature, fix

#283 fix: 마이페이지 투표참여및게시글 모달창, css 수정 , 헤더 뒤로가기 버튼 수정, 토스트창 마진 수정, 공유하기 모달 잘 뜨게 수정
  src/App.jsx
  src/components/common/mypage/MyVoteList.jsx
  src/components/layouts/headers/BackButton.jsx
  src/components/layouts/headers/UploadPageHeader.jsx
  src/pages/my/MyParticipatePage.jsx
  src/pages/my/MyQuestionPage.jsx
  src/routes.js
  src/styles/Container.jsx
Labels: 🔨 bug, fix

#287 feat: 댓글 개수 구현 및 url 복사시 toast 구현
  src/components/common/modal/ModalTemplate.jsx
  src/components/common/modal/ShareForm.jsx
  src/components/common/voteButton/EndButton.jsx
  src/components/common/voteButton/VoteBottom.jsx
  src/components/home/HomeLayout.jsx
  src/hooks/useLogin.js
  src/services/Cookie.js
  src/services/index.js
  src/services/login.js
  src/services/main.js
Labels: 🔥 feature

#289 fix: alert 창 , Icon 버그 수정
  src/components/common/Alert.jsx
  src/components/common/Icon.jsx
  src/components/common/modal/ChatWriteForm.jsx
  src/components/common/modal/ModalTemplate.jsx
  src/components/common/voteButton/VoteBottom.jsx
  src/components/common/voteButton/VoteHead.jsx
  src/components/home/HomeLayout.jsx
Labels: 🔨 bug

#330 feat: 이미지 리사이즈 코드 추가
  package-lock.json
  package.json
  src/components/upload/Img.jsx
Labels: 🔥 feature

#333 fix: 정렬 오류 해결
  src/components/home/HomeLayout.jsx
  src/pages/main/MainPage.jsx
Labels: 🔨 bug

#335 fix: 등록 두번 되는 버그 수정
  src/components/common/modal/ModalTemplate.jsx
  src/components/common/voteButton/EndButton.jsx
  src/components/common/voteButton/VoteHead.jsx
  src/components/upload/UploadButton.jsx
  src/services/index.js
Labels: 🔨 bug
