Repository Step3-kakao-tech-campus/Team11_FE, pull requests merged in 2023-10, with the labels that each got.

#63 fix: 메인 투표 컴포넌트 수정
  Goalajuma/package-lock.json
  Goalajuma/package.json
  Goalajuma/src/App.jsx
  Goalajuma/src/components/common/voteButton/MainButton.jsx
  Goalajuma/src/components/home/ButtonLayout.jsx
  Goalajuma/src/components/home/ButtonTest.js
  Goalajuma/src/components/home/HomeLayout.jsx
  Goalajuma/src/components/login/Input.jsx
  Goalajuma/src/components/login/InputGroup.jsx
  Goalajuma/src/components/upload/Input.jsx
  Goalajuma/src/components/upload/TextArea.jsx
  Goalajuma/src/pages/complete/CompletePage.jsx
  Goalajuma/src/pages/main/MainPage.jsx
  Goalajuma/src/pages/upload/UploadPage.jsx
  Goalajuma/src/styles/VotingBtnStyle.jsx
  Goalajuma/src/utils/Atom.js
Labels: enhancement

#89 전남대 _11조_골라주마_5주차
  Goalajuma/src/components/common/Icon.jsx
  Goalajuma/src/components/common/Img.jsx
  Goalajuma/src/components/common/modal/Chat.jsx
  Goalajuma/src/components/common/modal/ChatForm.jsx
  Goalajuma/src/components/common/modal/ChatWriteForm.jsx
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/common/modal/Practice.jsx
  Goalajuma/src/components/common/mypage/ActiveSign.jsx
  Goalajuma/src/components/common/mypage/MyList.jsx
  Goalajuma/src/components/common/mypage/MyPageUl.jsx
  Goalajuma/src/components/common/mypage/MyVoteList.jsx
  Goalajuma/src/components/common/mypage/MypageMainLi.jsx
  Goalajuma/src/components/common/mypage/Profile.jsx
  Goalajuma/src/components/common/mypage/mypageTestData.js
  Goalajuma/src/components/common/voteButton/ButtonLayout.jsx
  Goalajuma/src/components/common/voteButton/ButtonTest.js
  Goalajuma/src/components/common/voteButton/MainButton.jsx
  Goalajuma/src/components/common/voteButton/PercentNumber.jsx
  Goalajuma/src/components/common/voteButton/VoteButtom.jsx
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
  Goalajuma/src/components/home/HomeLayout.jsx
  Goalajuma/src/components/home/MainContent.jsx
  Goalajuma/src/components/home/Timer.jsx
  Goalajuma/src/components/layouts/AuthLayout.jsx
  Goalajuma/src/components/layouts/footers/Footer.jsx
  Goalajuma/src/components/layouts/headers/BackButton.jsx
  Goalajuma/src/components/layouts/headers/CategoryBox.jsx
  Goalajuma/src/components/layouts/headers/Dropdown.jsx
  Goalajuma/src/components/layouts/headers/HotPageHeader.jsx
  Goalajuma/src/components/layouts/headers/Main.jsx
  Goalajuma/src/components/layouts/headers/MainHeader.jsx
  Goalajuma/src/components/layouts/headers/MainLayout.jsx
  Goalajuma/src/components/layouts/headers/MyPageHeader.jsx
  Goalajuma/src/components/layouts/headers/SearchButton.jsx
  Goalajuma/src/components/layouts/headers/SubHeader.jsx
  Goalajuma/src/components/layouts/headers/SubMyPageHeader.jsx
  Goalajuma/src/components/layouts/headers/UploadPageHeader.jsx
  Goalajuma/src/components/test
  Goalajuma/src/pages/complete/CompletePage.jsx
  Goalajuma/src/pages/hot/HotPage.jsx
  Goalajuma/src/pages/main/MainPage.jsx
  Goalajuma/src/pages/my/MyParticipatePage.jsx
  Goalajuma/src/pages/my/MyQuestionPage.jsx
  Goalajuma/src/pages/my/Mypage.jsx
  Goalajuma/src/pages/test
  Goalajuma/src/styles/Container.jsx
  Goalajuma/src/utils/test
Labels: Request Review

#126 feat: 토스트 창 구현
  Goalajuma/package-lock.json
  Goalajuma/package.json
  Goalajuma/public/image/background2.png
  Goalajuma/src/components/common/Alert.jsx
  Goalajuma/src/components/common/Icon.jsx
  Goalajuma/src/components/common/modal/Modal.jsx
  Goalajuma/src/components/common/voteButton/ButtonTest.js
  Goalajuma/src/components/common/voteButton/MainButton.jsx
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
  Goalajuma/src/main.jsx
  Goalajuma/src/pages/main/MainPage.jsx
  Goalajuma/src/services/main.js
  Goalajuma/src/services/queries/mainQuery.js
  Goalajuma/src/styles/ModalStyle.jsx
  Goalajuma/src/styles/animation/FadeIn.js
Labels: 🔥 enhancement, ⭐️ fix

#135 design: 투표 종료 버튼 위치 조정 및 모달 내 작성자 보여주기
  Goalajuma/src/App.jsx
  Goalajuma/src/components/common/modal/Chat.jsx
  Goalajuma/src/components/common/modal/ChatWriteForm.jsx
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/common/modal/Practice.jsx
  Goalajuma/src/components/common/voteButton/EndButton.jsx
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
Labels: fix

#138 fix: 투표 종료 버튼 에러 수정
  Goalajuma/src/components/common/voteButton/EndButton.jsx
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
Labels: 🔨 bug

#142 feat: 카테고리 recoil 적용, 마이페이지 모달 연결
  Goalajuma/src/components/common/mypage/MyVoteList.jsx
  Goalajuma/src/components/layouts/headers/CategoryBox.jsx
  Goalajuma/src/components/layouts/headers/Dropdown.jsx
  Goalajuma/src/components/layouts/headers/MainHeader.jsx
  Goalajuma/src/components/layouts/headers/MainLayout.jsx
  Goalajuma/src/components/layouts/headers/MyPageHeader.jsx
  Goalajuma/src/components/layouts/headers/SubMyPageHeader.jsx
  Goalajuma/src/components/layouts/headers/UploadPageHeader.jsx
  Goalajuma/src/pages/upload/UploadPage.jsx
Labels: 🔥 feature

#160 feat: API 연결
  Goalajuma/src/assets/Loader.jsx
  Goalajuma/src/components/common/voteButton/ButtonLayout.jsx
  Goalajuma/src/components/common/voteButton/MainButton.jsx
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
  Goalajuma/src/components/home/HomeLayout.jsx
  Goalajuma/src/components/template/CompleteTemplate.jsx
  Goalajuma/src/components/template/HomeTemplate.jsx
  Goalajuma/src/components/template/HotTemplate.jsx
  Goalajuma/src/components/upload/UploadButton.jsx
  Goalajuma/src/pages/complete/CompletePage.jsx
  Goalajuma/src/pages/hot/HotPage.jsx
  Goalajuma/src/pages/main/MainPage.jsx
  Goalajuma/src/pages/my/MyParticipatePage.jsx
  Goalajuma/src/services/main.js
  Goalajuma/src/services/vote.js
  Goalajuma/src/styles/VotingBtnStyle.jsx
  Goalajuma/src/utils/UploadAtom.js
Labels: 🔥 feature, fix

#162 fix: header 카테고리, 스크롤 상단고정
  Goalajuma/src/App.jsx
  Goalajuma/src/components/common/ErrorScreen.jsx
  Goalajuma/src/components/common/ScrollToTop.js
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/common/voteButton/VoteBottom.jsx
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
  Goalajuma/src/components/home/HomeLayout.jsx
  Goalajuma/src/components/layouts/headers/CategoryBox.jsx
  Goalajuma/src/components/template/HotTemplate.jsx
  Goalajuma/src/components/upload/CategoryNDeadLine.jsx
  Goalajuma/src/components/upload/UploadButton.jsx
  Goalajuma/src/main.jsx
  Goalajuma/src/pages/complete/CompletePage.jsx
  Goalajuma/src/pages/hot/HotPage.jsx
  Goalajuma/src/pages/main/MainPage.jsx
  Goalajuma/src/services/main.js
  Goalajuma/vite.config.js
Labels: 🔨 bug, 🔥 feature, fix

#166 feat: 공유하기 기능 구현 (페이스북, 트위터, 현재 url 복사하기)
  Goalajuma/package-lock.json
  Goalajuma/package.json
  Goalajuma/src/components/common/modal/ModalLayout.jsx
  Goalajuma/src/components/common/modal/ShareForm.jsx
  Goalajuma/src/pages/login/LoginPage.jsx
  Goalajuma/src/pages/signup/SignUpPage.jsx
  Goalajuma/src/utils/LoginState.js
Labels: 🔥 feature

#170 feat: 검색페이지 구현
  Goalajuma/src/App.jsx
  Goalajuma/src/components/common/Icon.jsx
  Goalajuma/src/components/common/Img.jsx
  Goalajuma/src/components/common/mypage/Profile.jsx
  Goalajuma/src/components/common/voteButton/VoteBottom.jsx
  Goalajuma/src/components/common/voteButton/VoteHead.jsx
  Goalajuma/src/components/layouts/headers/SearchButton.jsx
  Goalajuma/src/components/search/SearchInput.jsx
  Goalajuma/src/pages/my/ProfileModal.jsx
  Goalajuma/src/pages/search/SearchPage.jsx
  Goalajuma/src/routes.js
  Goalajuma/src/services/search.js
  Goalajuma/src/styles/GlobalStyle.jsx
  Goalajuma/src/utils/SearchAtom.js
Labels: 🔨 bug, 🔥 feature

#158 전남대_11조_골라주마_7주차
  Goalajuma/src/components/common/mypage/ActiveSign.jsx
  Goalajuma/src/components/common/mypage/MyPageUl.jsx
  Goalajuma/src/components/common/mypage/MyVoteList.jsx
  Goalajuma/src/components/common/mypage/MypageMainLi.jsx
  Goalajuma/src/components/common/mypage/Profile.jsx
  Goalajuma/src/components/layouts/footers/Footer.jsx
  Goalajuma/src/components/layouts/headers/CategoryBox.jsx
  Goalajuma/src/components/layouts/headers/SubMyPageHeader.jsx
  Goalajuma/src/pages/my/MyParticipatePage.jsx
  Goalajuma/src/pages/my/MyQuestionPage.jsx
  Goalajuma/src/pages/my/Mypage.jsx
  Goalajuma/src/utils/HeaderAtom.js
Labels: ✨ Request Review

#181 feat: 로그인, 회원가입 api 연결
  Goalajuma/src/pages/login/LoginPage.jsx
  Goalajuma/src/pages/signup/SignUpPage.jsx
  Goalajuma/src/services/login.js
  Goalajuma/src/services/mypage.js
  Goalajuma/src/services/queries/mainQuery.js
  Goalajuma/src/services/signup.js
  Goalajuma/src/services/test
Labels: 🔥 feature
